name: Flutter Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # adjust if your Flutter version is different

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (release, split per ABI)
        run: flutter build apk --release --split-per-abi

      - name: Upload APKs (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk
